version: "3"
services:
  # Selenium サーバを起動するコンテナ
  selenium:
    image: seleniarm/standalone-chromium
    container_name: selenium-chrome
    ports:
      # Selenium サーバに接続するポート
      - "4444:4444"
      # VNC で接続するポート
      - "5900:5900"
      # Selenium サーバのログを出力するポート
      - "7900:7900"
    # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"
    volumes:
      - $(pwd)/data-set:/home/seluser/Downloads
  # poetryの開発環境を構築するコンテナ
  poetry-app: 
    restart: always
    build: .
    image: poetry-app:1.0
    container_name: poetry-app
    working_dir: /app
    tty: true
    volumes:
      - .:/app
  # jupyter-notebookを立ち上げるコンテナ
  jupyter-notebook:
    restart: always
    build: ./create-map
    image: jupyter-notebook:1.0
    volumes:
      - ./create-map/:/app/create-map
    ports:
      - 8888:8888
    tty: true

